/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ec5b13",
        "primary-landing": "#ff9157",
        "background-light": "#f8f6f6",
        "background-dark": "#221610",
        "inverse-surface": "#fcf9f8",
        "on-primary": "#531e00",
        "on-surface": "#ffffff",
        "on-tertiary-fixed-variant": "#003580",
        "on-error-container": "#ffd2c8",
        "on-tertiary-fixed": "#00163d",
        "secondary-container": "#006d35",
        "primary-fixed": "#ff7a2c",
        "on-secondary": "#005d2c",
        "tertiary-fixed": "#8eafff",
        "surface-container-high": "#20201f",
        "primary-fixed-dim": "#f46800",
        "secondary-dim": "#24f07e",
        "surface-tint": "#ff9157",
        "secondary-fixed-dim": "#24f07e",
        "error": "#ff7351",
        "tertiary": "#6e9bff",
        "error-container": "#b92902",
        "on-tertiary": "#001d4e",
        "primary-container": "#ff7a2c",
        "on-primary-container": "#401600",
        "on-primary-fixed": "#000000",
        "surface-dim": "#0e0e0e",
        "on-secondary-fixed-variant": "#006832",
        "outline": "#767575",
        "surface": "#0e0e0e",
        "surface-variant": "#262626",
        "surface-bright": "#2c2c2c",
        "secondary": "#3fff8b",
        "on-surface-variant": "#adaaaa",
        "on-secondary-fixed": "#004820",
        "inverse-on-surface": "#565555",
        "on-tertiary-container": "#000000",
        "surface-container": "#1a1a1a",
        "on-error": "#450900",
        "secondary-fixed": "#3fff8b",
        "background": "#0e0e0e",
        "surface-container-low": "#131313",
        "tertiary-fixed-dim": "#77a1ff",
        "surface-container-lowest": "#000000",
        "error-dim": "#d53d18",
        "on-primary-fixed-variant": "#4f1d00",
        "outline-variant": "#484847",
        "inverse-primary": "#a04200",
        "primary-dim": "#ff7520",
        "surface-container-highest": "#262626",
        "on-secondary-container": "#e3ffe4",
        "tertiary-dim": "#0f6df3",
        "tertiary-container": "#2778fe",
        "on-background": "#ffffff"
      },
      fontFamily: {
        "display": ["Public Sans", "sans-serif"],
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
